backend/src/logging/logger.ts
Commented file logging option from the Winston logger as it was causing issues in the OpenShift deployment
=> commented logging to file

forms-flow-ai/epd-forms/Site Information Request Application.json
=> fixed notes visible for site-owner in SIR form

forms-flow-ai/forms-flow-ai-ee/forms-flow-web/src/components/Form/constants/FormTable.js
Localized content was wrapped with i18next's `t` function directly instead of its React hook. This PR removes the former and replaces it with the translation function provided by the `useTranslation` hook in `react-i18next`.
I've previewed the changes on my local environment:
=> fix: Use `i18next`'s hook to translate localized content

forms-flow-ai/forms-flow-ai-ee/forms-flow-web/src/components/Form/Item/View.js
This PR includes the micro-frontend relevant to the error message appearing in the `Summary of Site Condition` form. Now, instead of `Error while Submission.`, we will show `Submission cannot be done.`. This will keep it consistent with other toasts in the application and will support translation via the existent localization profiles.
To reproduce it, follow the steps below:
1. Click on `Submit New` in the `Summary of Site Condition` form.
1. Open your Dev Tools Console and set the network to `offline`.
1. Fill the form as appropriate.
1. Submit the form and check the error message.
If all steps were followed correctly, you should see a toast with the following error message:
Localization works with it:
N/A
=> fix: error message coming from the backend

forms-flow-ai/forms-flow-ai-ee/forms-flow-bpm/docker-compose.yml, forms-flow-ai/forms-flow-ai-ee/forms-flow-bpm/processes/Common/CommonEmailWorkflow.bpmn, forms-flow-ai/forms-flow-ai-ee/forms-flow-bpm/templates/nir_application.ftl, forms-flow-ai/forms-flow-ai-ee/forms-flow-bpm/templates/nom_application.ftl, forms-flow-ai/forms-flow-ai-ee/forms-flow-bpm/templates/request_updated.ftl, forms-flow-ai/forms-flow-ai-ee/forms-flow-bpm/templates/sds_application.ftl, forms-flow-ai/forms-flow-ai-ee/forms-flow-bpm/templates/sir_application_approved.ftl, forms-flow-ai/forms-flow-ai-ee/forms-flow-bpm/templates/sir_application_rejected.ftl, forms-flow-ai/forms-flow-ai-ee/forms-flow-bpm/templates/sosc_application.ftl, forms-flow-ai/forms-flow-ai-ee/forms-flow-bpm/templates/srcr_application.ftl
This PR introduces a significant enhancement to our application's configuration by adding a new environment variable, `APP_HOST`. The primary purpose of this addition is to improve the flexibility and adaptability of our application across different environments such as development, testing, and production.
- **Introduction of `APP_HOST` Environment Variable**: 
- The `APP_HOST` variable holds the host address where our application is running. Its versatility allows us to dynamically fetch resources like email logos corresponding to the environment in use. This change is particularly beneficial for ensuring that our application remains consistent and reliable across various deployment stages.
- I've chosen a generic name (`APP_HOST`) for broader applicability, anticipating future …
=> feat!: change the URL used for the logo in the email templates

etl/ReadMe.md, etl/register-postgres-source-connector.json
When postgres db connection is timeout, connector should retry. This fix resolves issue partly by retrying after 30 sec. If the db is not back within 30 sec, connector will be shut down. Helps to reconnect after short network glitches.
SRS-211
=> fix for connection retry issue

frontend/Site/src/app/features/site/dto/SiteFilterConfig.ts, frontend/Site/src/app/features/site/filters/SiteFilterForm.test.jsx, frontend/Site/src/app/features/site/filters/SiteFilterForm.tsx
=> remove unused code.

forms-flow-ai/epd-forms/Site Risk Classification Report.json, forms-flow-ai/epd-forms/bundling/Site Risk Classification Report.json
Change the checkbox for exposure pathways in the Risk Classification Report to use a radio select instead of a checkbox select. Reasoning: We expect exactly one answer.
Fixes # SRS-267
I have uploaded this form and validated that it now uses a radio input.
=> Update Site Risk Classification Report

cats-frontend/src/App.css, cats-frontend/src/app/components/navigation/Footer.css, cats-frontend/src/app/components/navigation/Header.css, cats-frontend/src/app/components/navigation/MobileNavMenu.css, cats-frontend/src/app/components/navigation/SideBar.css, cats-frontend/src/app/components/table/Table.css, cats-frontend/src/app/components/table/header/TableHeader.css, cats-frontend/src/app/features/people/Search.css
Fix global font-family, add appropriate font fallbacks.
Also removed redundant font-family css rules.
=> CATS: fix FE fonts

docker-compose.yml
Correct indentation in docker-compose.yml
This fixes the following issue:
```
❯ docker-compose up -d database
validating /Users/bolaney/Source/github.com/bcgov/nr-epd-digital-services/docker-compose.yml: (root) Additional property userapi_doc is not allowed
nr-epd-digital-services on  dev [$!?] via 🐳 colima via  v23.7.0 
❯ docker-compose up -d database
validating /Users/bolaney/Source/github.com/bcgov/nr-epd-digital-services/docker-compose.yml: (root) Additional property frontend is not allowed
```
=> fix: docker-compose incorrect indentation

cats-frontend/src/app/components/navigation/navigationpills/INavigationPills.ts, cats-frontend/src/app/components/navigation/navigationpills/NavigationPills.test.tsx, cats-frontend/src/app/components/navigation/navigationpills/NavigationPills.tsx, cats-frontend/src/app/features/applications/application/ApplicationDetails.tsx, cats-frontend/src/app/features/navigation/NavigationPillsConfig.tsx
This change makes NavigationPills component router-friendly and aware of search params.
- Selecting a navigation pill should set search params to `?tabKey=tabValue`
- Refreshing the page with the valid URL search params present should take you directly to that tab
I updated the application page to support this change, the url should be updated to `/application?tab=participants` when using the tabs.
Fixes [SRS-867](https://env-epd.atlassian.net/browse/SRS-867)
=> SRS-867: CATS Application page - set current tab in URL search params

cats-frontend/package.json
#789 added a config argument to the codegen script.
I missed the fact that we also need to add the same argument to codegen when running `dev` script. This PR fixes it.
=> chore: CATS - fix codegen when running concurrently with dev build

.github/workflows/ci-dev.yaml, .github/workflows/pr-open.yml
Re-enable cats unit tests on PR open and PR to dev. Disable sonarcloud for the time being until we can get the secret set up to enable it to pass sucessfully.
=> chore: re-add cats unit tests, disable sonarcloud for the time being

backend/cats/src/app/entities/appParticipant.entity.ts, backend/cats/src/migrations/1742493703576-master-script.ts
There are few fields which could be null, thus changed them in the entity class for App Pariticipant
---
- [Backend](https://nr-epd-digital-services-829-backend.apps.silver.devops.gov.bc.ca)
- [Frontend](https://nr-epd-digital-services-829-frontend.apps.silver.devops.gov.bc.ca)
=> fix: Add few fields to be nullable in AppParticipant table

backend/cats/src/app/services/application/applicationSearch.service.ts
Fixes a bad condition on the application search query. An analysis of the data
shows that the removed conditions are not valid.
---
- [Backend](https://nr-epd-digital-services-838-backend.apps.silver.devops.gov.bc.ca)
- [Frontend](https://nr-epd-digital-services-838-frontend.apps.silver.devops.gov.bc.ca)
=> fix: Remove bad condition from appsearch query

backend/cats/src/app/cats.module.ts, backend/cats/src/app/dto/application/createApplication.dto.ts, backend/cats/src/app/resolvers/application/application.resolver.spec.ts, backend/cats/src/app/services/appType/appType.service.spec.ts, backend/cats/src/app/services/appType/appType.service.ts, backend/cats/src/app/services/application/application.service.spec.ts, backend/cats/src/app/services/application/application.service.ts, forms-flow-ai/forms-flow-ai-ee/forms-flow-web/package-lock.json
This change is to pick up the application type id from the database based on the application type passed from FF submission.
---
- [Backend](https://nr-epd-digital-services-853-backend.apps.silver.devops.gov.bc.ca)
- [Frontend](https://nr-epd-digital-services-853-frontend.apps.silver.devops.gov.bc.ca)
- …
=> feat: changes to pick app type from db

backend/cats/src/app.module.ts, backend/cats/src/app/filters/graphql-exception.filter.ts, backend/cats/src/app/guards/mock-auth.guard.ts
With our current keycloak setup, it's difficult to develop and test graphql queries/mutations without also building the front-end that uses them because almost every query requires user authentication. What I and other devs on the team tend to do is commenting out the auth guards when you need to call the API from the sandbox/postman/some-other-client. This approach has two major issues: 
1. It's easy to forget to put the guards back
2. You lose the access to the `@AuthenticatedUser` object
This PR makes two keys changes:
-  Added a `MockAuthGuard` that injects a mock user object into the request/context, allowing the app to bypass Keycloak authentication when the environment variable `MOCK_AUTH=true` is set.
- Updated AppModule to use MockAuthGuard as the global APP_GUARD when in mock …
=> chore: SRS-917 - add auth mock mode, improve auth error handling

cats-frontend/src/apollo.ts, cats-frontend/src/index.tsx
Has this ever happened to you? You're trying to debug a graphql query made by your front end, so you open the network tab of your dev tools and all you see is 
And then you need to click each request to find the one you're looking for? Well not anymore! 
This change appends the operation's name so that the query/mutation you're looking for is identifiable at a glance
**Note**: I only added this to requests initiated by Apollo Client. While it is possible to use a similar pattern in axios-based queries, I didn't add it because:
1. It's not possible to infer the operation's name at runtime. We'd need pass the name to every call to axios instance, which results in a lot more code
2. Given the alternatives, I really don't think we should continue using the axios-based pattern.
3. I'm not …
=> chore: SRS-918 surface operation names in Graphql requests

backend/cats/package-lock.json, backend/cats/package.json, backend/cats/src/app/cats.module.ts, backend/cats/src/app/dto/response/timesheetDayResponse.ts, backend/cats/src/app/dto/timesheetDay.dto.ts, backend/cats/src/app/entities/timesheetDay.entity.ts, backend/cats/src/app/resolvers/timesheetDay.resolver.spec.ts, backend/cats/src/app/resolvers/timesheetDay.resolver.ts, backend/cats/src/app/services/timesheetDay.service.spec.ts, backend/cats/src/app/services/timesheetDay.service.ts, backend/cats/src/migrations/1746549000000-create-timesheet-day.ts, cats-frontend/src/generated/types.ts
In this PR:
- New TimeSheetDay entity and database migration
- Graphql mutation for creating and updating timesheet days (combined into one "upsert" operation capable of processing batch upserts
- Graphql query for fetching timesheet days for application within time range, grouped by assigned staff
Fixes [SRS-785](https://env-epd.atlassian.net/browse/SRS-785)
Examples:
```graphql
mutation {
upsertTimesheetDays(input: {
entries: [
{ applicationId: 1, personId: 629, date: "2025-06-01", hours: 8 },
{ applicationId: 1, personId: 629, date: "2025-06-02", hours: 7.5, timesheetDayId: 2 }
]
}) {
data {
id
applicationId
personId
date
hours
}
message
success
}
}
```
Response:
```json
{
"data": {
"upsertTimesheetDays": {
"data": [
{
"id": 11, …
```
=> feat: SRS-785: API to create, update and get timesheet days

cats-frontend/src/app/components/input-controls/InputControls.tsx, cats-frontend/src/app/features/applications/application/applicationTabs/appParticipants/ParticipantsTable.tsx, cats-frontend/src/app/helpers/utility.ts
This issue was leading to inconistent dates showed on UI vs selected in datepicker
- Date on datepicker in edit mode was not in sync
- Date selected on edit mode was not in sync
Issue: eg new Date('2025-10-02') converts the selected date to UTC midnight and thus what we see in PST is 1 day before date. 
What has been done to fix the issue: 
// FIX: Ensures the value passed to DatePicker is always a valid Date object or null.
// - Handles both string dates (e.g., '2025-06-03') and Date objects consistently.
// - Converts date strings to local Date objects using parseLocalDate.
// - Normalizes all Date objects to local midnight using normalizeDate, to avoid timezone-related UI issues.
// - Applies normalization in both table display mode and edit mode for consistent rendering and …
=> fix: SRS -948 : Fix date issue

backend/cats/initDB.sh, charts/app/templates/backend/templates/deployment.yaml
---
- [Backend](https://nr-epd-digital-services-992-backend.apps.silver.devops.gov.bc.ca)
- [Frontend](https://nr-epd-digital-services-992-frontend.apps.silver.devops.gov.bc.ca)
=> fix: Combine -seed and -init initContainers, only have one now, and updated seed logic in initDB.sh

forms-flow-ai/forms-flow-ai-ee/forms-flow-web-root-config/src/index.ejs
Fix the spelling mistake on the web apps favicon - "Site Remediaton Services" to Site Remediation Services
---
- [Backend](https://nr-epd-digital-services-1095-backend.apps.silver.devops.gov.bc.ca)
- [Frontend](https://nr-epd-digital-services-1095-frontend.apps.silver.devops.gov.bc.ca)
=> fix: the spelling mistake on the web apps favicon - "Site Remediaton Services" to Site Remediation Services
